name: ipucd13_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animate_do: ^3.3.4
  audioplayers: ^6.1.0
  calendar_view: ^1.2.0
  card_swiper: ^3.0.1
  change_app_package_name: ^1.4.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^17.2.3
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  go_router: ^14.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  open_file: ^3.5.8
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_1.png"
  min_sdk_android: 21 # android min sdk min:16, defa

flutter:
  uses-material-design: true

  assets:
    - .env.local
    - .env.production
    - .env.post_production
    - assets/loaders/
    - assets/images/
    - assets/videos/
    - assets/gif/

flutter_native_splash:
  color: "#00338d"
  color_dark: "#00338d"
  
  # Asegúrate de que esta ruta sea correcta
  background_image: "assets/images/logo_texto_color_splash.png"
  
  android_12:
    color: "#00338d"
    color_dark: "#00338d"
    # Asegúrate de que esta ruta sea correcta y que la imagen cumpla con los requisitos de tamaño para Android 12
    image: "assets/images/logo_texto_color_splash.png"

  # Configuraciones específicas de plataforma para asegurar consistencia
  color_android: "#00338d"
  color_dark_android: "#00338d"
  color_ios: "#00338d"
  color_dark_ios: "#00338d"

  # Descomenta estas líneas si no quieres generar splash screen para web
  # android: true
  # ios: true
  # web: false